<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/26 0026
 * Time: 上午 9:02
 */
namespace app\index\model;
use think\Model;
class Index extends Model{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        echo 'bbbbbbbbbb';
    }
}