<?php
namespace app\index\model;
use think\Model;
class User extends Model{

    protected $pk = 'uid';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        echo 'aaaaaaaaaaaa';
    }
}
?>